name: KBOT_CICD

on: push

jobs:
  ci:  
    name: CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Authenticate with Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Run test
        run: make test
      - name: Authenticate Docker with GCR
        run: echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io
      - name: Build&Push
        env:
          APP: "kbot"  
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make image push